Repository TeskaLabs/seacat-auth, pull requests merged in 2023-03, with the labels that each got.

#146 Assign role or tenant to multiple credentials at once
  CHANGELOG.md
  seacatauth/authz/role/handler/roles.py
  seacatauth/authz/role/service.py
  seacatauth/exceptions.py
  seacatauth/tenant/handler.py
  seacatauth/tenant/providers/abc.py
  seacatauth/tenant/providers/mongodb.py
  seacatauth/tenant/service.py
Labels: enhancement

#168 Client features refactoring
  CHANGELOG.md
  seacatauth/client/handler.py
  seacatauth/client/service.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/pkce.py
Labels: breaking change

#157 Client URI validation
  CHANGELOG.md
  seacatauth/client/service.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/provisioning/service.py
  test/__init__.py
  test/test_oauth_url.py
Labels: enhancement, breaking change

#173 Speed up searching in audit log
  CHANGELOG.md
  seacatauth/audit/service.py
Labels: bug

#174 Flatten the login dict in login prologue
  seacatauth/authn/handler.py
Labels: bug
