Repository TeskaLabs/seacat-auth, pull requests merged in 2023-08, with the labels that each got.

#240 Batman docs updated
  CHANGELOG.md
  Dockerfile
  docs/integrations/elk.md
  docs/reference/session.md
  etc/seacatauth.conf
  example/docker/nginx-conf/nginx.conf
  example/docker/seacatauth-conf/seacatauth.conf
  example/nginx-config/nginx-anonymous.conf
  example/nginx-config/nginx-http.conf
  example/nginx-config/nginx-multisubdomain.conf
  seacatauth/__init__.py
  seacatauth/app.py
  seacatauth/audit/service.py
  seacatauth/authn/handler.py
  seacatauth/authn/login_session.py
  seacatauth/authn/m2m.py
  seacatauth/authn/service.py
  seacatauth/authn/webauthn/service.py
  seacatauth/authz/resource/service.py
  seacatauth/batman/handler.py
  seacatauth/client/service.py
  seacatauth/cookie/handler.py
  seacatauth/cookie/service.py
  seacatauth/credentials/change_password/service.py
  seacatauth/credentials/handler.py
  seacatauth/credentials/providers/abc.py
  seacatauth/credentials/registration/service.py
  seacatauth/exceptions.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/service.py
  seacatauth/openidconnect/session.py
  seacatauth/otp/service.py
  seacatauth/session/adapter.py
  seacatauth/session/handler.py
  seacatauth/session/service.py
Labels: documentation

#241 Add SSL CA file and API key support in ELK Batman
  CHANGELOG.md
  seacatauth/batman/elk.py
Labels: enhancement

#239 Fix resource rename flow
  CHANGELOG.md
  seacatauth/authz/resource/handler.py
  seacatauth/authz/resource/service.py
Labels: bug

#245 Upgrade to Python 3.11
  CHANGELOG.md
  Dockerfile
  seacatauth/credentials/service.py
Labels: enhancement

#249 OpenID Connect Discovery
  CHANGELOG.md
  example/docker/nginx-conf/nginx.conf
  seacatauth/openidconnect/__init__.py
  seacatauth/openidconnect/handler/discovery.py
  seacatauth/openidconnect/handler/introspect.py
  seacatauth/openidconnect/handler/public_keys.py
  seacatauth/openidconnect/handler/session.py
  seacatauth/openidconnect/handler/token.py
  seacatauth/openidconnect/handler/userinfo.py
  seacatauth/openidconnect/service.py
Labels: enhancement
