Repository TeskaLabs/seacat-auth, pull requests merged in 2023-06, with the labels that each got.

#211 Session performance improvement
  CHANGELOG.md
  seacatauth/session/service.py
Labels: enhancement

#210 Impersonation REST API
  CHANGELOG.md
  seacatauth/authn/handler.py
  seacatauth/authn/service.py
  seacatauth/authz/utils.py
  seacatauth/cookie/service.py
  seacatauth/openidconnect/service.py
  seacatauth/session/builders.py
Labels: enhancement

#214 Fix track ID transfer
  CHANGELOG.md
  seacatauth/session/service.py
Labels: bug

#216 Unify batman and cookie sessions
  CHANGELOG.md
  docs/getting-started/recommended-deployment.md
  docs/getting-started/teskalabs-seacat-auth-token-architecture.drawio.svg
  docs/integrations/elk.md
  docs/integrations/index.md
  docs/integrations/teskalabs-seacat-auth-cookie-flow.drawio.svg
  mkdocs.yml
  seacatauth/__init__.py
  seacatauth/batman/handler.py
  seacatauth/batman/service.py
  seacatauth/client/handler.py
  seacatauth/cookie/service.py
  seacatauth/openidconnect/handler/token.py
  seacatauth/session/adapter.py
Labels: enhancement, breaking change

#217 Configurable anonymous session expiration
  CHANGELOG.md
  seacatauth/__init__.py
  seacatauth/cookie/service.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/session/service.py
Labels: enhancement

#226 Update modtime of active sessions
  CHANGELOG.md
  seacatauth/__init__.py
  seacatauth/session/service.py
Labels: enhancement

#221 Common AES key
  CHANGELOG.md
  seacatauth/__init__.py
  seacatauth/app.py
  seacatauth/otp/service.py
  seacatauth/session/service.py
Labels: breaking change

#219 Reduce last login reads
  CHANGELOG.md
  seacatauth/audit/service.py
  seacatauth/credentials/handler.py
  seacatauth/openidconnect/service.py
Labels: enhancement, breaking change
