Repository TeskaLabs/seacat-auth, pull requests merged in 2023-09, with the labels that each got.

#258 Re-lock webauthn package version
  CHANGELOG.md
  Dockerfile
Labels: bug

#260 Add 'id_token_signing_alg_values_supported' to OIDP discovery endpoint response
  CHANGELOG.md
  seacatauth/openidconnect/handler/discovery.py
Labels: bug

#257 Unified SMTP config
  CHANGELOG.md
  seacatauth/communication/builders/email.py
  seacatauth/communication/email_smtp.py
Labels: enhancement, breaking change

#232 Algorithmic anonymous sessions
  CHANGELOG.md
  seacatauth/__init__.py
  seacatauth/app.py
  seacatauth/cookie/handler.py
  seacatauth/cookie/service.py
  seacatauth/credentials/handler.py
  seacatauth/generic.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/handler/token.py
  seacatauth/openidconnect/handler/userinfo.py
  seacatauth/openidconnect/service.py
  seacatauth/session/adapter.py
  seacatauth/session/algorithmic.py
  seacatauth/session/service.py
Labels: enhancement

#263 Implement authorize parameter `nonce`
  CHANGELOG.md
  seacatauth/cookie/service.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/service.py
  seacatauth/openidconnect/session.py
  seacatauth/session/adapter.py
Labels: bug

#265 Initialize Zookeeper
  CHANGELOG.md
  seacatauth/app.py
Labels: enhancement

#262 Add Sentry service
  CHANGELOG.md
  Dockerfile
  seacatauth/app.py
Labels: enhancement

#266 Validate redirect URI in authorize request
  CHANGELOG.md
  seacatauth/__init__.py
  seacatauth/app.py
  seacatauth/client/service.py
  seacatauth/generic.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/service.py
  seacatauth/provisioning/service.py
Labels: enhancement, breaking change

#267 Fix private key provisioning
  CHANGELOG.md
  seacatauth/app.py
Labels: bug

#268 Support MongoDB version 3.6
  CHANGELOG.md
  seacatauth/tenant/providers/mongodb.py
Labels: enhancement

#261 Public invitation API
  CHANGELOG.md
  seacatauth/authz/resource/service.py
  seacatauth/credentials/registration/handler.py
Labels: enhancement, breaking change

#285 Implement tenant label
  CHANGELOG.md
  seacatauth/tenant/handler.py
  seacatauth/tenant/providers/mongodb.py
  seacatauth/tenant/schemas.py
  seacatauth/tenant/service.py
Labels: enhancement

#290 Fix validation when creation_data incomplete
  CHANGELOG.md
  seacatauth/credentials/policy.py
Labels: bug

#287 Add openid discovery uris to config defaults
  seacatauth/external_login/providers/facebook.py
  seacatauth/external_login/providers/generic.py
  seacatauth/external_login/providers/github.py
  seacatauth/external_login/providers/google.py
  seacatauth/external_login/providers/mojeid.py
  seacatauth/external_login/providers/office365.py
Labels: documentation, enhancement

#269 Don't use upsertor in Audit service
  CHANGELOG.md
  seacatauth/audit/service.py
  seacatauth/events.py
Labels: bug

#289 Github user email
  CHANGELOG.md
  seacatauth/external_login/providers/github.py
Labels: enhancement

#292 External login JWT validation
  CHANGELOG.md
  seacatauth/external_login/handler.py
  seacatauth/external_login/providers/facebook.py
  seacatauth/external_login/providers/generic.py
  seacatauth/external_login/providers/github.py
  seacatauth/external_login/providers/google.py
  seacatauth/external_login/providers/mojeid.py
  seacatauth/external_login/providers/office365.py
  seacatauth/external_login/service.py
Labels: enhancement
