Repository TeskaLabs/seacat-auth, pull requests merged in 2023-10, with the labels that each got.

#293 AppleID login
  CHANGELOG.md
  docs/config/external-login.md
  seacatauth/external_login/handler.py
  seacatauth/external_login/providers/__init__.py
  seacatauth/external_login/providers/appleid.py
  seacatauth/external_login/providers/facebook.py
  seacatauth/external_login/providers/generic.py
  seacatauth/external_login/providers/github.py
  seacatauth/external_login/providers/google.py
Labels: enhancement

#294 Preserve nonce when redirecting to login
  CHANGELOG.md
  seacatauth/openidconnect/handler/authorize.py
Labels: bug

#297 Fix webauthn username
  CHANGELOG.md
  seacatauth/authn/webauthn/handler.py
  seacatauth/authn/webauthn/service.py
Labels: bug

#256 FIDO metadata
  CHANGELOG.md
  seacatauth/authn/webauthn/service.py
Labels: enhancement

#301 Move NGINX introspection endpoints to private API
  CHANGELOG.md
  docs/config/cookies.md
  docs/integrations/elk.md
  docs/integrations/index.md
  example/docker/nginx-conf/nginx.conf
  example/nginx-config/nginx-anonymous.conf
  example/nginx-config/nginx-http.conf
  example/nginx-config/nginx-multisubdomain.conf
  seacatauth/authn/m2m.py
  seacatauth/batman/handler.py
  seacatauth/cookie/handler.py
  seacatauth/middleware.py
  seacatauth/openidconnect/handler/discovery.py
  seacatauth/openidconnect/handler/introspect.py
  seacatauth/openidconnect/service.py
Labels: bug, enhancement, breaking change

#311 Move NGINX introspection endpoints to private API (post-fix)
  CHANGELOG.md
  seacatauth/authn/m2m.py
  seacatauth/batman/handler.py
  seacatauth/cookie/handler.py
  seacatauth/openidconnect/handler/introspect.py
Labels: bug, enhancement, breaking change

#300 Authorization for websocket requests
  CHANGELOG.md
  example/nginx-config/nginx-websocket-authorization.conf
  seacatauth/generic.py
  seacatauth/openidconnect/handler/introspect.py
Labels: enhancement

#312 Silence stable log messages
  CHANGELOG.md
  seacatauth/app.py
  seacatauth/batman/grafana.py
  seacatauth/external_login/providers/generic.py
  seacatauth/openidconnect/handler/introspect.py
  seacatauth/session/service.py
Labels: enhancement

#296 Allow all standard OIDC authorize params
  CHANGELOG.md
  seacatauth/authn/handler.py
  seacatauth/client/service.py
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/service.py
  seacatauth/openidconnect/utils.py
Labels: enhancement, breaking change

#313 Fix default authorize parameter values when redirecting
  CHANGELOG.md
  seacatauth/openidconnect/handler/authorize.py
  seacatauth/openidconnect/pkce.py
  seacatauth/openidconnect/service.py
Labels: bug
